blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
      _method:  GET


blogger_blog_aboutpage:
    path:     /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
      _method:  GET

blogger_blog_contactpage:
    path:     /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
      _method:  GET|POST

blogger_blog_faqpage:
    path:     /faq
    defaults: { _controller: BloggerBlogBundle:Page:faq }
    requirements:
      _method:  GET

blogger_blog_blogshow:
    path:     /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    methods:  GET
    requirements:
      id: \d+

blogger_blog_comment_create:
    path:     /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    methods:  POST
    requirements:
      blog_id: \d+